### ISSUE TITLE
Sometimes it can take more that 10 minutes for the 3Mbps stream to become available

### ISSUE THREAD

**Issue by wunderbrot** [Darkness4/fc2-live-dl-go#38]
I've noticed that on some streams the 3Mbps quality won't show up for more than 10 minutes.  Would it be possible to add a periodic check, or even just a restart after x minutes option when downloading at a lower quality than requested?

**Comment by Darkness4** [comment]
I'll think about it. Thanks for the suggestion.

**Comment by Darkness4** [comment]
Feature is being tracked on the [feat/quality-switching](https://github.com/Darkness4/fc2-live-dl-go/tree/feat/quality-switching) branch. It seems to be working but there is a visible cut off/rewind during the switch (the same fragment is being downloaded I guess).

**Comment by Darkness4** [comment]
This feature will be available starting with version 1.7.
